; Script generated by Antigravity AI Coding Assistant for MacSpoof Installer

[Setup]
AppName=KernelMacSpoofer
AppVersion=1.0.0
AppPublisher=Zhi
AppPublisherURL=https://github.com/Yuezhiui/KernelMacSpoofer
AppSupportURL=https://github.com/Yuezhiui/KernelMacSpoofer/issues
AppUpdatesURL=https://github.com/Yuezhiui/KernelMacSpoofer/releases
DefaultDirName={autopf}\KernelMacSpoofer
DefaultGroupName=KernelMacSpoofer
UninstallDisplayIcon={app}\MacSpoof.exe
Compression=lzma2/max
SolidCompression=yes
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
OutputDir=c:\Users\Yue\Desktop\Spoof
OutputBaseFilename=KernelMacSpoofer-Setup-v1.0.0-x64
PrivilegesRequired=admin

[Files]
Source: "c:\Users\Yue\Desktop\Spoof\MacSpoof\MacSpoof\bin\Release\net8.0-windows10.0.19041.0\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\MacSpoof"; Filename: "{app}\MacSpoof.exe"
Name: "{group}\Uninstall MacSpoof"; Filename: "{uninstallexe}"
Name: "{autodesktop}\MacSpoof"; Filename: "{app}\MacSpoof.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Run]
Filename: "{app}\MacSpoof.exe"; Description: "{cm:LaunchProgram,MacSpoof}"; Flags: nowait postinstall skipifsilent runascurrentuser
